### PR TITLE
211 bakcend: validate nickname alphanum

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Review by peterjah — APPROVED** [review]

**Comment by SlnPons** [comment]
This was not needed.... It's ok to keep it as it has been implemented but for product question, please reach out next time ;)

**Comment by Thykof** [comment]
This PR prevent user to enter special char in the nickname, to implement rule: 

image

**Comment by SlnPons** [comment]
@Thykof can you explain what you have implemented please? 
In the rule I asked to check if the special character error is not a bug so it's not 100% clear to me what you've done:
1. Prevent special characters and so didn't solve the bug
2. Solve the bug and so all characters are accepted for the nickname

**Comment by Thykof** [comment]
I didn't look for a potential bug, I force the nickname to contain only letters, min/maj, number, `-` and `_`, no accent, no special char.

I spoke with @peterjah , there is no bug, but if we want to allow any char, we will have to implement something to make it work.

**Comment by SlnPons** [comment]
@gregLibert we discussed together that there was a bug on thyra wallet and that was the reason special characters were not 

@Thykof I'm really against Devs implementing product rules. What is the rational behind no special char or accent? Does it prevent URL encoding? I don't understand the link between the rule implemented and the URL /API calls

**Comment by SlnPons** [comment]
@Thykof thanks for your explanations. As discussed, the rule you implemented will prevent people from using any special chars which include other alphabetical letters etc... 
So it's good to me. Looking forward to testing it.

**Pull request merged**
