### PR TITLE
fixed selector import

### PR DESCRIPTION
**Pull request by pivilartisant**
The import for the account selector needed to be fixed after some ui-kit refactoring

### CODE REVIEW

**Review by peterjah — CHANGES_REQUESTED** [review]
can you make the changes in react-ui-kit for everything to be exported properly??
I should be possible to import components like this:
`
import { Button, AccountSelector,  MassaToken} from '@massalabs/react-ui-kit';
`

**Comment by pivilartisant** [comment]
> can you make the changes in react-ui-kit for everything to be exported properly?? It should be possible to import components like this: `import { Button, AccountSelector, MassaToken} from '@massalabs/react-ui-kit';`


I wish.... unfortunately we have a problem with imports like that  : 

Screenshot from 2023-05-15 12-19-22

**Comment by peterjah** [comment]
It seems to work fine for Button, so why not for AccountSelector and MassaToken?

**Comment by Thykof** [comment]
it's something related to `import React from 'react';` even if React is not used in the component

**Comment by pivilartisant** [comment]
> It seems to work fine for Button, so why not for AccountSelector and MassaToken?

it works on the go server but not with vite... so I guess best we can do is dev with specific paths and delete them once we are making the pr ? 
@peterjah  @Thykof

**Comment by peterjah** [comment]
> > It seems to work fine for Button, so why not for AccountSelector and MassaToken?
> 
> it works on the go server but not with vite... so I guess best we can do is dev with specific paths and delete them once we are making the pr ? @peterjah @Thykof

sorry i don't understand :/ 
but lets forget about this, its not critical

**Review by peterjah — APPROVED** [review]

**Comment by Thykof** [comment]
> > It seems to work fine for Button, so why not for AccountSelector and MassaToken?
> 
> it works on the go server but not with vite... so I guess best we can do is dev with specific paths and delete them once we are making the pr ? @peterjah @Thykof

yes if you want

**Pull request merged**
