### PR TITLE
Add Logo plugin wallet

### PR DESCRIPTION
**Pull request by 0xMazout**

### CODE REVIEW

**Review by Thykof — APPROVED** [review]

**Review by peterjah — APPROVED** [review]

**Comment by SlnPons** [comment]
I don't understand why I can't see the wallet logo updated... 
I can see the commit on the repo but when doing the release it doesn't appear: https://github.com/massalabs/thyra-plugin-wallet/releases 

--> still have this: 
image

Do you know why?

**Comment by 0xMazout** [comment]
No i was thinking it was working , and i tested it on the plugin Hello World but it's the same behavior.. 

I don't know why. Tomorrow in the morning will ask for help . 

It seems all the plugin built with go swagger method doesn't care of Svg files

**Comment by SlnPons** [comment]
@0xMazout could you explain (very quickly) what was the issue for tracability and knowledge sharing please?
thanks a lot

**Comment by 0xMazout** [comment]
It's was a Path problem.

In the construction of Plugins like wallet and Hello world .

The build path is not displayed in the code and we don't have any clues about it anywhere.

So Nathan and i have used the console to do retro-engineering on it to find a file correctly loaded and use the same path to retrieve the path of the file

You have to setup the right Path of the file containing the logo manually 

The debug is painfull but the issue is pretty easy

**Pull request merged**
