### PR TITLE
move tests to related folder

### PR DESCRIPTION
**Pull request by mazmassa**
We are moving the tests files to a specific related folder in order to keep a clean structure.

<table><tr><td><b>Before</b></td> <td><b>After</b></td></tr><tr>
<td> 

```js
\wallet
    - file1.go
    - file1_test.go
    - file2.go
    - file2_test.go
    - ...  
```

</td>
<td>

```js
\wallet
    - file1.go
    - file2.go
    - ...
    \tests
        - file1_test.go
        - file2_test.go
        - ...  
```

</td>
</tr>
</table>

### CODE REVIEW

**Comment by gregLibert** [comment]
> We are moving the tests files to a specific related folder in order to keep a clean structure.
> 
> Before	After
> ```js
> \wallet
>     - file1.go
>     - file2.go
>     - ...
>     \tests
>         - file1_test.go
>         - file2_test.go
>         - ...  
> ```
> 
> ```js
> \wallet
>     - file1.go
>     - file1_test.go
>     - file2.go
>     - file2_test.go
>     - ...  
> ```

Two things:
- your code is actually doing the opposite of what you said
- go is expecting to have both test and code file in the same directory. Changing that is maybe possible but will be certainly painful at some point.

**Review by gregLibert — CHANGES_REQUESTED** [review]
:no_good:

**Comment by mazmassa** [comment]
> * your code is actually doing the opposite of what you said
I did no code. Just moved to a /tests folder.

> * go is expecting to have both test and code file in the same directory. Changing that is maybe possible but will be certainly painful at some point.
Really!? We can't have that in a specific folder!?

**Comment by mazmassa** [comment]
> 🙅

Haven't got the point here neither!? That means this should not be done!? It's wrong!? Can I have more info!?

**Comment by mazmassa** [comment]
Unfortunately that's the way it works on GO! Same dir for tests... :( 

Closing it!

**Pull request closed without merging**
